name = "utilityroom-club"
main = "src/index.tsx"
compatibility_date = "2025-04-02"

[build]
jsx_factory = "h"

[[kv_namespaces]]
binding = "PROJECTS"
id = "47e06254587f46cfa4904cd122d770b5"

[[kv_namespaces]]
binding = "USERS"
id = "efdf6c84461145da86c85d34893ee69b"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "utilityroom-club-assets"

[[routes]]
pattern = "utilityroom.club"
custom_domain = true
