name = "auth-tobys-cloud"
main = "src/index.ts"
compatibility_date = "2025-04-02"

[dev]
port = 8788

[[kv_namespaces]]
binding = "USERS"
id = "9aa195d53abc46818a9ffa61bbc019af"

[[d1_databases]]
binding = "AUDIT"
database_name = "auth-tobys-cloud-audit"
database_id = "a3b3bbf1-56dc-42f1-aa4e-22408ef57bd0"
migrations_dir = "migrations"

[[routes]]
pattern = "auth.tobys.cloud"
zone_name = "tobys.cloud"
custom_domain = true

[[routes]]
pattern = "auth.tobys.cloud/*"
zone_name = "tobys.cloud"
