import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const postsDir = path.join(root, "posts");
const outFile = path.join(root, "src", "generated-posts.ts");

const files = fs
  .readdirSync(postsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();

const entries = files.map((file) => {
  const slug = file.replace(/\.md$/, "");
  const body = fs.readFileSync(path.join(postsDir, file), "utf8");
  return `  ${JSON.stringify(slug)}: ${JSON.stringify(body)},`;
});

const source = `// Generated by tools/generate-posts.mjs — do not edit by hand.
export const POSTS: Record<string, string> = {
${entries.join("\n")}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, source);
console.log(`wrote ${files.length} posts → src/generated-posts.ts`);
