#!/usr/bin/env ruby

def cross_platform_open_url(url)
  url = url.match?(/^http/) ? url : "http://#{url}"

  puts "opening url #{url}"

  case RUBY_PLATFORM
  when /linux/
    spawn "xdg-open '#{url}'"
  when /darwin/
    spawn "open '#{url}'"
  else
    puts 'I do not know how to open web pages on your platform'
  end
end

case ARGV.first

when /^graf/
  cross_platform_open_url 'localhost:3000'
  Process.wait spawn(
    "kubectl --namespace monitoring port-forward svc/grafana 3000",
    in: STDIN, out: STDOUT, err: STDERR,
  )
when /^prom/
  cross_platform_open_url 'localhost:9090'
  Process.wait spawn(
    "kubectl --namespace monitoring port-forward svc/prometheus-k8s 9090",
    in: STDIN, out: STDOUT, err: STDERR,
  )

when /^alert/
  cross_platform_open_url 'localhost:9093'
  Process.wait spawn(
    "kubectl --namespace monitoring port-forward svc/alertmanager-main 9093",
    in: STDIN, out: STDOUT, err: STDERR,
  )

when /^monzo/
  cross_platform_open_url 'localhost:9036'
  Process.wait spawn(
    "kubectl --namespace monitoring port-forward svc/monzo-exporter 9036",
    in: STDIN, out: STDOUT, err: STDERR,
  )

when /toby.codes/, /codes/
  cross_platform_open_url 'https://toby.codes'
when /tobys.cloud/, /cloud/
  cross_platform_open_url 'https://tobys.cloud'

else
  puts <<~HELP
    $0 usage:

    You can open the following mgmt apps via forwarding:

     - $0 grafana
     - $0 prometheus
     - $0 alertmanager
     - $0 monzo

    You can open the following service apps over the internet:

     - $0 www.toby.codes
     - $0 www.tobys.cloud
  HELP
end
