#!/usr/bin/env ruby

def cross_platform_open_url(url)
  url = url.match?(/^http/) ? url : "http://#{url}"

  puts "opening url #{url}"

  case RUBY_PLATFORM
  when /linux/
    spawn "xdg-open '#{url}'"
  when /darwin/
    spawn "open '#{url}'"
  else
    puts 'I do not know how to open web pages on your platform'
  end
end

case ARGV.first

when /^conc/
  cross_platform_open_url '127.0.0.1:8080'
  Process.wait spawn(
    "kubectl --namespace tsp-system port-forward svc/tsp-system-concourse-web 8080",
    in: STDIN, out: STDOUT, err: STDERR,
  )
when /^graf/
  cross_platform_open_url 'localhost:3000'
  Process.wait spawn(
    "kubectl --namespace tsp-system port-forward svc/tsp-system-grafana 3000:80",
    in: STDIN, out: STDOUT, err: STDERR,
  )
when /^prom/
  cross_platform_open_url 'localhost:9090'
  Process.wait spawn(
    "kubectl --namespace tsp-system port-forward svc/tsp-system-prometheus-oper-prometheus 9090",
    in: STDIN, out: STDOUT, err: STDERR,
  )

when /^monzo/
  cross_platform_open_url 'localhost:9036'
  Process.wait spawn(
    "kubectl --namespace tsp-system port-forward svc/monzo-exporter 9036",
    in: STDIN, out: STDOUT, err: STDERR,
  )

when /toby.codes/, /codes/
  cross_platform_open_url 'https://toby.codes'
when /tobys.cloud/, /cloud/
  cross_platform_open_url 'https://tobys.cloud'

else
  puts <<~HELP
    #{$0} usage:

    You can open the following mgmt apps via forwarding:

     - $0 concourse
     - $0 grafana
     - $0 prometheus
     - $0 alertmanager
     - $0 monzo

    You can open the following service apps over the internet:

     - $0 www.toby.codes
     - $0 www.tobys.cloud
  HELP
end
