---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sites

images:
  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: 6548cdb423ccd4f7c89a8c15336576bbd3ed2c18

resources:
  - namespace.yaml
  - acceptance-tests.yaml
