---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sites

images:
  - name: ghcr.io/tlwr/www-tobys-cloud-acceptance
    newTag: 956529e7c18f422d3b1a71469807b02910a883e3

resources:
  - namespace.yaml
  - acceptance-tests.yaml
